### ISSUE TITLE
License Change? Contributions?

### ISSUE THREAD

**Issue by JayV30** [veracity-tech/vtc-lrs#1]
Hi there. Thanks for this cool project! As it stands now, this project can be used to experiment, but the restrictive license basically prevents any _actual_ use.

In addition, due to the code compilation / minifying, no one can effectively contribute to or extend this.

It would appear that your organization does not want to open-source this? Any chance of changing the license and / or sharing the uncompiled code? I hope I'm not coming off as rude, that is not intended as you have every right to manage your project however you want. I'm just exploring the options available to developers for a node-express LRS.

Cheers!

**Comment by rchadwic** [comment]
Hi Jay,

As you can probably see, we're not really maintaining this any longer. This code should mostly work, but we've moved on to a different model.  You can find a free to use but not open LRS server on the downloads page at https://lrs.io. 

I do think there is a large open source Node.js LRS out there.  They've pretty much got the market for such a thing covered, so we're not going to try to compete. 

If you're looking to extend an LRS with other capabilities, check out the plugin documentation at 
https://lrs.io/docs/manual/plugins/

**Comment by JayV30** [comment]
Thanks for the quick reply! I'll check out your LRS server in my research. Wishing you and your colleagues continued success.
